### ISSUE TITLE
Caused by: java.io.IOException: Task did not succeed and did not report an error

### ISSUE THREAD

**Issue by sixcorners** [sshtools/maverick-synergy#75]
version 3.0.10
I'm getting this error:

Caused by: java.io.IOException: Task did not succeed and did not report an error
	at com.sshtools.client.SshClient.doTask(SshClient.java:288)

This error message stinks. The reason it happens is because the throwable is getting saved here:
com.sshtools.common.ssh.ConnectionAwareTask#lastError
but the error is getting read from here:
com.sshtools.client.tasks.AbstractSessionTask#lastError

**Comment by sixcorners** [comment]
Caused by: java.io.IOException: Failed to connect to x:22

These error messages aren't very good.

**Comment by ludup** [comment]
The tone of your report makes me question why I'm even bothering to comment. 

I don't know how else to communicate a failure to connect to the host and port you tried to connect to. You could be more constructive and give me an example of what you'd like to see. 

As for the other previous message that **stinks** :|  if the exception were stored in the correct place, then it wouldn't say that. You discovered a bug, but rather than submit a PR you just posted something that only served to p**s of the maintainer.

Thank you for your input.

**Comment by sixcorners** [comment]
Sorry. Didn't mean anything against the project or the maintainers.

I think the error message should say something like the domain name couldn't be resolved or the tcp connection was refused or the permission was denied and here is what the server said or there was a connection timeout or there was a read timeout or the server closed the connection.
